baseurl = "https://matthekim.github.io/aether"
title = "Hugo Themes - aether"
author = "Joe Hutchinson"
canonifyurls = true
paginate = 3
theme = "aether"
themesDir = "../../" 

[params]
    brand = "aether"
    description = "aether Hugo theme for blogs"
    headshotimg = "img/faceshot.jpg"

[markup]
  [markup.highlight]
    style = "igor"

    DefaultContentLanguage = "en"
[languages]
  [languages.en]
    title = "My New Hugo i18n Site"
    languageName = "English"
    weight = 1
  [languages.gr]
    title = "Η Νεα μου Ιστιοσελιδα"
    languageName = "Greek"
    weight = 2
defaultContentLanguageInSubdir = true
